default:
  image: rust:1.79
  cache: &global_cache
    policy: pull
    unprotect: true
    key:
      files:
        - Cargo.lock
    paths:
      - target/
    when: on_success

stages:
  - test
  - publish

test:
  stage: test
  script:
    - cargo test

benchmarks:
  stage: test
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    - cargo bench

publish:
  stage: publish
  script:
    - cargo publish
  rules:
    - if: $CI_COMMIT_TAG

publish dry run:
  stage: publish
  script:
    - cargo publish --dry-run