default:
  image: rust:1.79

stages:
  - test
  - publish

test:
  stage: test
  script:
    - cargo test

benchmarks:
  stage: test
  script:
    - cargo bench

publish:
  stage: publish
  script:
    - cargo publish
  rules:
    - if: $CI_COMMIT_TAG

publish dry run:
  stage: publish
  script:
    - cargo publish --dry-run