[package]
name = "rigz_vm"
description = "Register based VM for rigz"
version = "0.4.1"
edition = "2021"
readme = "README.md"
license = "MIT"
repository = "https://gitlab.com/magicfoodhand/rigz_vm"

[dependencies]
indexmap = "2.3.0"
once_cell = "1.19.0"
