[package]
name = "rigz_runtime"
version = "0.2.3"
edition = "2021"
description = "Handles parsing and converting rigz to its VM instructions, no AST available (use tree-sitter-rigz instead)"
readme = "README.md"
license = "MIT"
repository = "https://gitlab.com/magicfoodhand/rigz_runtime"

[dependencies]
indexmap = "2.3.0"
logos = "0.14.1"
rigz_vm = { version = "0.14.1" }
once_cell = "1.19.0"
log = "0.4.22"