[package]
name = "rigz_vm"
description = "Register based VM for rigz"
version = "0.14.1"
edition = "2021"
readme = "README.md"
license = "MIT"
repository = "https://gitlab.com/magicfoodhand/rigz_vm"

[dependencies]
crossbeam = "0.8"
dyn-clone = "1.0.17"
indexmap = "2.3.0"
log = "0.4.22"
nohash-hasher = "0.2.0"
once_cell = "1.19.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
pretty_env_logger = "0.5.0"

[[bench]]
name = "number_benchmarks"
harness = false

[[bench]]
name = "value_benchmarks"
harness = false

[[bench]]
name = "vm_benchmarks"
harness = false
