[package]
name = "rigz_runtime"
version = "0.3.0"
edition = "2021"
description = "Handles parsing and converting rigz to its VM instructions (for syntax highlighting use tree-sitter-rigz instead)"
readme = "README.md"
license = "MIT"
repository = "https://gitlab.com/magicfoodhand/rigz_runtime"

[dependencies]
indexmap = "2.6.0"
logos = "0.14"
rigz_vm = { version = "0.31" }
# rigz_vm = { path = "rigz_vm" } # local testing - create symbolic link, ln -s <path>/rigz_vm
log = "0.4"
serde_json = "1.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
pretty_env_logger = "0.5.0"

[[bench]]
name = "eval_benchmarks"
harness = false