[package]
name = "rigz_runtime"
version = "0.3.0"
edition = "2021"
description = "Handles parsing and converting rigz to its VM instructions (for syntax highlighting use tree-sitter-rigz instead)"
readme = "README.md"
license = "MIT"
repository = "https://gitlab.com/inapinch/rigz/rigz_runtime"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
logos = "0.14"
rigz_ast = { workspace = true }
rigz_ast_derive = { workspace = true }
rigz_vm = { workspace = true }
log = "0.4"
serde_json = "1.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
pretty_env_logger = "0.5.0"

[[bench]]
name = "eval_benchmarks"
harness = false