[package]
name = "rigz_vm"
description = "Register based VM for rigz"
version = "0.36.0"
edition = "2021"
readme = "README.md"
license = "MIT"
repository = "https://gitlab.com/inapinch/rigz/crates/vm"
keywords = ["rigz", "vm"]

[features]
default = ["derive"]
derive = ["dep:proc-macro2", "dep:quote"]
log_std_out = []

[dependencies]
crossbeam = "0.8.4"
derive_more = { version = "1.0.0", features = ["into_iterator"] }
dyn-clone = "1.0.17"
indexmap = { version = "2.7.0", features = ["serde"] }
itertools = "0.14.0"
log = "0.4.22"
log-derive = "0.4.1"
quote = { version = "1", optional = true }
proc-macro2 = { version = "1.0", optional = true }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "number_benchmarks"
harness = false

[[bench]]
name = "value_benchmarks"
harness = false

[[bench]]
name = "vm_benchmarks"
harness = false
